// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebGanadera.App.Persistencia;

namespace WebGanadera.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WebGanadera.App.Dominio.Ganado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("MedicoId")
                        .HasColumnType("int");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<string>("raza")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.ToTable("Ganado");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Ganado");
                });

            modelBuilder.Entity("WebGanadera.App.Dominio.HistoriaClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("FechaAplicacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedAplicante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumDosis")
                        .HasColumnType("int");

                    b.Property<string>("Periodicidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VacunaApli")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Historia");
                });

            modelBuilder.Entity("WebGanadera.App.Dominio.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroTel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("WebGanadera.App.Dominio.Vacuna", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FechaVen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Labo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("vacuna");
                });

            modelBuilder.Entity("WebGanadera.App.Dominio.GanadoCitaMedica", b =>
                {
                    b.HasBaseType("WebGanadera.App.Dominio.Ganado");

                    b.Property<string>("FechaControl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModConsulta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumEjemplar")
                        .HasColumnType("int");

                    b.Property<int?>("vacunaId")
                        .HasColumnType("int");

                    b.HasIndex("vacunaId");

                    b.HasDiscriminator().HasValue("GanadoCitaMedica");
                });

            modelBuilder.Entity("WebGanadera.App.Dominio.Ganadero", b =>
                {
                    b.HasBaseType("WebGanadera.App.Dominio.Persona");

                    b.Property<int?>("GanadoPId")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("GanadoPId");

                    b.HasDiscriminator().HasValue("Ganadero");
                });

            modelBuilder.Entity("WebGanadera.App.Dominio.Veterinario", b =>
                {
                    b.HasBaseType("WebGanadera.App.Dominio.Persona");

                    b.Property<int?>("vacunaId")
                        .HasColumnType("int");

                    b.Property<string>("veterinaria")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("vacunaId");

                    b.HasDiscriminator().HasValue("Veterinario");
                });

            modelBuilder.Entity("WebGanadera.App.Dominio.Ganado", b =>
                {
                    b.HasOne("WebGanadera.App.Dominio.Veterinario", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("WebGanadera.App.Dominio.GanadoCitaMedica", b =>
                {
                    b.HasOne("WebGanadera.App.Dominio.Vacuna", "vacuna")
                        .WithMany()
                        .HasForeignKey("vacunaId");

                    b.Navigation("vacuna");
                });

            modelBuilder.Entity("WebGanadera.App.Dominio.Ganadero", b =>
                {
                    b.HasOne("WebGanadera.App.Dominio.Ganado", "GanadoP")
                        .WithMany()
                        .HasForeignKey("GanadoPId");

                    b.Navigation("GanadoP");
                });

            modelBuilder.Entity("WebGanadera.App.Dominio.Veterinario", b =>
                {
                    b.HasOne("WebGanadera.App.Dominio.Vacuna", "vacuna")
                        .WithMany()
                        .HasForeignKey("vacunaId");

                    b.Navigation("vacuna");
                });
#pragma warning restore 612, 618
        }
    }
}
